name: creamoteama
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.0+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #webview_flutter: ^4.5.0
  #flutter_blue: ^0.8.0
  #flutter_blue_plus: ^1.31.13
  #carousel_slider: ^4.2.1
  flutter_blue_plus: ^1.31.13
  #smooth_page_indicator: ^1.0.0+2
  #fluttertoast: ^8.2.4
  permission_handler: ^11.2.0
  fluttertoast: ^8.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/puzzle/
    - images/button/
    - images/slider/
    - images/start/
    - images/slider_hard/
    - images/slider_initial/
    - images/slider_middle/
    - images/start/creamo_logo.png
    - images/start/start_background.png
    - images/start/start_button_1.png
    - images/start/use_button_1.png
    - images/slider/content1.png
    - images/slider/content2.png
    - images/slider/content3.png
    - images/slider/content4.png
    - images/slider/content5.png
    - images/slider/content6.png
    - images/slider/content7.png
    - images/slider/content8.png
    - images/slider/content9.png
    - images/slider/content10.png
    - images/slider/content11.png
    - images/slider/content12.png
    - images/slider/content13.png
    - images/slider/content14.png
    - images/slider/content15.png
    - images/slider/content16.png
    - images/slider/content17.png
    - images/slider/content18.png
    - images/slider/content19.png
    - images/slider/content20.png
    - images/slider/content21.png
    - images/slider/content22.png
    - images/slider/content23.png
    - images/slider/content24.png
    - images/slider/content25.png
    - images/slider/content26.png

    - images/puzzle/block1.png
    - images/puzzle/block2.png
    - images/puzzle/block3.png
    - images/puzzle/block4.png
    - images/puzzle/block5.png
    - images/puzzle/block6.png
    - images/puzzle/block7.png
    - images/puzzle/block8.png
    - images/puzzle/block9.png
    - images/puzzle/block10.png
    - images/puzzle/block11.png
    - images/puzzle/block12.png
    - images/puzzle/block13.png
    - images/puzzle/block14.png
    - images/puzzle/block15.png
    - images/puzzle/block16.png
    - images/puzzle/block17.png
    - images/puzzle/block18.png
    - images/puzzle/block19.png
    - images/puzzle/block20.png
    - images/puzzle/block21.png
    - images/puzzle/block22.png
    - images/puzzle/block23.png
    - images/puzzle/block24.png
    - images/puzzle/block25.png
    - images/puzzle/block26.png
    - images/puzzle/block27.png
    - images/puzzle/block28.png
    - images/puzzle/block29.png
    - images/puzzle/block30.png
    - images/puzzle/block31.png
    - images/puzzle/block32.png
    - images/puzzle/block33.png
    - images/puzzle/block34.png
    - images/puzzle/block35.png
    - images/puzzle/block36.png
    - images/puzzle/block37.png
    - images/puzzle/block38.png
    - images/puzzle/block39.png
    - images/puzzle/block40.png
    - images/puzzle/block41.png
    - images/puzzle/block42.png
    - images/puzzle/block43.png
    - images/puzzle/block44.png

    - images/button/button1.png
    - images/button/button2.png
    - images/button/button4.png
    - images/button/button3.png
    - images/button/button6.png
    - images/button/button5.png
    - images/button/run.png
    - images/button/trash.png
    - images/button/reset.png
    - images/button/home.png
    - images/button/poweroff.png
    - images/button/easy.png
    - images/button/middle.png
    - images/button/hard.png
    - images/slider_initial/1.png
    - images/slider_initial/2.png
    - images/slider_initial/2.png
    - images/slider_middle/1.png
    - images/slider_middle/2.png
    - images/slider_middle/3.png
    - images/slider_hard/1.png
    - images/slider_hard/2.png
    - images/slider_hard/3.png

    - images/backgrounds/splash_background.png
    - images/backgrounds/background.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
images/puzzle/block5:
  png: